files:
  - source: /**/*.resx
    ignore:
      - '*.*.resx'
    translation: /**/%file_name%.%two_letters_code%.resx
    languages_mapping: {
      "two_letters_code" : {
        "pt-BR" : "pt-BR",
      }
    }
